CREATE DATABASE banco;

USE banco;

CREATE TABLE CATEGORIES (
    ID INT PRIMARY KEY IDENTITY,
    RISK VARCHAR (25) NOT NULL,
    SECTOR VARCHAR (25) NOT NULL,
    VALUE_FROM MONEY NOT NULL,
    VALUE_UNTIL MONEY NOT NULL 
);

INSERT INTO CATEGORIES VALUES ('LOWRISK', 'PUBLIC', 0.00, 1000000.00);
INSERT INTO CATEGORIES VALUES ('MEDIUMRISK', 'PUBLIC', 1000000.01, 922337203685477.58);
INSERT INTO CATEGORIES VALUES ('HIGHRISK', 'PRIVATE', 1000000.00, 922337203685477.58);


CREATE TABLE INPUT_OUTPUT_LOG (
    ID INT PRIMARY KEY IDENTITY,
    CLIENT_SECTOR VARCHAR (25) NOT NULL,
    CLIENT_VALUE MONEY NOT NULL,
    RISK_RESULT VARCHAR(25),
    DATE_RESULT DATETIME
);

INSERT INTO INPUT_OUTPUT_LOG (CLIENT_SECTOR, CLIENT_VALUE) VALUES ('PRIVATE', 2000000);
INSERT INTO INPUT_OUTPUT_LOG (CLIENT_SECTOR, CLIENT_VALUE) VALUES ('PUBLIC', 400000);
INSERT INTO INPUT_OUTPUT_LOG (CLIENT_SECTOR, CLIENT_VALUE) VALUES ('PUBLIC', 500000);
INSERT INTO INPUT_OUTPUT_LOG (CLIENT_SECTOR, CLIENT_VALUE) VALUES ('PUBLIC', 3000000);
